name: Internal Issue
description: Plugin developer topics, for helping contributors keep track of changes behind the scenes - NOT for user questions or requests
labels: ["type: internal"]
body:
  - type: markdown
    attributes:
      value: |
        ## About this form
        This form is **only** for tracking topics by developers of the Tasks plugin and other contributors to the source code, like refactoring, dependency updates and similar.
        It is not intended for user questions, which should go in [Discussions/Q&A](https://github.com/obsidian-tasks-group/obsidian-tasks/discussions/categories/q-a), please - and will be closed if added here.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the change. Why is it necessary?
    validations:
      required: true

  - type: textarea
    id: required-steps
    attributes:
      label: Required Steps
      description: |
        If you know of particular files that needto be changed, or other particular actions, please record them here.
    validations:
      required: false

  - type: textarea
    id: how-to-test
    attributes:
      label: How to Test
      description: |
        If you know how this change will be tested, please record ideas here.
    validations:
      required: false
